# Read the Docs Configuration File
# See https://docs.readthedocs.io/en/stable/config-file/v2/

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

python:
  version: 3.11
  install:
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: false

# Optional: Enable PDF and EPUB builds
formats:
  - pdf
  - epub

# Redirect to the main documentation
redirects:
  old-page: new-page
