name: adapt_env
channels:
  - conda-forge
dependencies:
  - numpy
  - xarray
  - pandas
  - scipy
  - arm_pyart
  - opencv
  - scikit-image
  - matplotlib
  - cartopy>=0.21
  - netCDF4
  - tqdm
  - h5py
  - proj
  - hdf5
  - libnetcdf
  - pillow
  - pyyaml
  - pip
  - pytest>=7.0
  - pytest-cov
  - sphinx>=7.0
  - networkx
  - pyproj
  - contextily
  - pyarrow
  - pydata-sphinx-theme
  - pydantic
  - pip:
      - nexradaws
      - sphinx-autodoc-typehints
      - myst-parser>=2.0
